version: "1.0"

services:
  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:80"
    networks:
      - app_network
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongodbusers
    volumes:
      - users_mongo_backup:/data/db
    networks:
      - app_network

volumes:
  users_mongo_backup:

networks:
  app_network:
    driver: bridge
